// Siglas de Órganos de la PNP — Anexo 01 del Manual
export const ORGANOS_PNP = [
  { nombre: 'Dirección General', siglas: 'DIRGEN' },
  { nombre: 'Estado Mayor General', siglas: 'EMG' },
  { nombre: 'Inspectoría General', siglas: 'IG' },
  { nombre: 'Dirección Nacional de Operaciones Policiales', siglas: 'DIRNOP' },
  { nombre: 'Dirección Nacional de Gestión Institucional', siglas: 'DIRNGI' },
  { nombre: 'Secretaría General', siglas: 'SECGEN' },
  { nombre: 'Dirección de Inteligencia', siglas: 'DIRINT' },
  { nombre: 'Dirección de Comunicación e Imagen', siglas: 'DIRCOIMA' },
  { nombre: 'Dirección de Asuntos Internacionales', siglas: 'DIRASINT' },
  { nombre: 'Dirección Ejecutiva de Administración', siglas: 'DIREJADM' },
  { nombre: 'Dirección Ejecutiva de Planeamiento y Presupuesto', siglas: 'DIREPP' },
  { nombre: 'Dirección Ejecutiva de Tecnología, Inf., Com. y Estadística', siglas: 'DIRETICE' },
  { nombre: 'Dirección Ejecutiva de Personal', siglas: 'DIREJPER' },
  { nombre: 'Dirección Ejecutiva de Infraestructura y Equipamiento', siglas: 'DIREIE' },
  { nombre: 'Dirección Ejecutiva de Asesoría Jurídica', siglas: 'DIREAJ' },
  { nombre: 'Dirección Ejecutiva de Sanidad', siglas: 'DIREJSAN' },
  { nombre: 'Dirección Ejecutiva de Apoyo al Policía', siglas: 'DIREAP' },
  { nombre: 'Dirección Ejecutiva de Educación y Doctrina', siglas: 'DIREED' },
  { nombre: 'Dirección Ejecutiva de Seguridad Integral', siglas: 'DIRESI' },
  { nombre: 'Dirección Ejecutiva de Inv. Criminal y Apoyo a la Justicia', siglas: 'DIREICAJ' },
  { nombre: 'Dirección Ejecutiva de Fuerzas Especiales', siglas: 'DIREFE' },
  { nombre: 'Dirección Ejecutiva de Criminalística', siglas: 'DIREJCRI' },
  { nombre: 'Dirección Ejecutiva de Seguridad Ciudadana', siglas: 'DIRESC' },
  { nombre: 'Dirección Ejecutiva de Anti Drogas', siglas: 'DIREAD' },
  { nombre: 'Dirección Ejecutiva Contra el Terrorismo', siglas: 'DIRECT' },
  { nombre: 'Dirección Ejecutiva de Tránsito y Seguridad Vial', siglas: 'DIRETSV' },
  { nombre: 'Dirección Ejecutiva de Turismo', siglas: 'DIREJTUR' },
  { nombre: 'Dirección Ejecutiva de Medio Ambiente', siglas: 'DIREMA' },
  { nombre: 'Frente Policial', siglas: 'FFPP' },
  { nombre: 'Región Policial', siglas: 'REGPOL' },
  { nombre: 'Comando Único Policial', siglas: 'CUP' },
];

// Regiones Policiales — Anexo 02 del Manual
export const REGIONES_PNP = [
  { nombre: 'Amazonas', siglas: 'REGPOL AMA' },
  { nombre: 'Ancash', siglas: 'REGPOL ANC' },
  { nombre: 'Apurímac', siglas: 'REGPOL APU' },
  { nombre: 'Arequipa', siglas: 'REGPOL AQP' },
  { nombre: 'Ayacucho', siglas: 'REGPOL AYA' },
  { nombre: 'Cajamarca', siglas: 'REGPOL CAJ' },
  { nombre: 'Callao', siglas: 'REGPOL CALL' },
  { nombre: 'Cusco', siglas: 'REGPOL CUS' },
  { nombre: 'Huánuco', siglas: 'REGPOL HCO' },
  { nombre: 'Huancavelica', siglas: 'REGPOL HCA' },
  { nombre: 'Ica', siglas: 'REGPOL ICA' },
  { nombre: 'Junín', siglas: 'REGPOL JUN' },
  { nombre: 'Lambayeque', siglas: 'REGPOL LAM' },
  { nombre: 'La Libertad', siglas: 'REGPOL LAL' },
  { nombre: 'Lima', siglas: 'REGPOL LIM' },
  { nombre: 'Loreto', siglas: 'REGPOL LOR' },
  { nombre: 'Madre de Dios', siglas: 'REGPOL MDD' },
  { nombre: 'Moquegua', siglas: 'REGPOL MOQ' },
  { nombre: 'Pasco', siglas: 'REGPOL PAS' },
  { nombre: 'Piura', siglas: 'REGPOL PIU' },
  { nombre: 'Puno', siglas: 'REGPOL PUN' },
  { nombre: 'San Martín', siglas: 'REGPOL SAM' },
  { nombre: 'Tumbes', siglas: 'REGPOL TUM' },
  { nombre: 'Tacna', siglas: 'REGPOL TAC' },
  { nombre: 'Ucayali', siglas: 'REGPOL UCA' },
];
